//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCadernetaPediatrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.ControlePediatrios = new HashSet<ControlePediatrio>();
        }
    
        public long IdPaciente { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public decimal Peso { get; set; }
        public decimal Estatura { get; set; }
        public decimal PC { get; set; }
        public decimal PT { get; set; }
        public string TipoSanguineo { get; set; }
        public bool Ictericia { get; set; }
        public string ReflexoVermelho { get; set; }
        public string TestePezinho { get; set; }
        public string TriagemAuditiva { get; set; }
        public string Observacoes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlePediatrio> ControlePediatrios { get; set; }
    }
}
